[2016-03-10 11:22:34 +0000] [8238] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    resp.write(item)
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 329, in write
    raise TypeError('%r is not a byte' % arg)
TypeError: ['x=1'] is not a byte
[2016-03-10 11:22:56 +0000] [8238] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    resp.write(item)
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 329, in write
    raise TypeError('%r is not a byte' % arg)
TypeError: [''] is not a byte
[2016-03-10 11:23:06 +0000] [8238] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    resp.write(item)
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 329, in write
    raise TypeError('%r is not a byte' % arg)
TypeError: [''] is not a byte
[2016-03-10 11:26:36 +0000] [8286] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    resp.write(item)
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 329, in write
    raise TypeError('%r is not a byte' % arg)
TypeError: [''] is not a byte
[2016-03-10 11:26:47 +0000] [8286] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    resp.write(item)
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 329, in write
    raise TypeError('%r is not a byte' % arg)
TypeError: ['x=1'] is not a byte
[2016-03-10 11:31:24 +0000] [8328] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    resp.write(item)
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 329, in write
    raise TypeError('%r is not a byte' % arg)
TypeError: ['x=1'] is not a byte
[2016-03-10 11:31:43 +0000] [8328] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    resp.write(item)
  File "/home/tayfen/develop/stepic/web_apps/stepic_venv/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 329, in write
    raise TypeError('%r is not a byte' % arg)
TypeError: [''] is not a byte
